### PR TITLE
update how to get latest release

### LINKED ISSUE #26: bug: update the way to get latest release
In this workflow, it downloads v4.9.1 as the latest release. 

see https://github.com/lean-ja/lean-by-example/actions/runs/9883761323/job/27299040801#step:3:1

but actually v4.10.0-rc2 is the latest.
This is a bug of the way to get latest release. 

important note: this issue make the workflow fail

### PR DESCRIPTION
**Pull request by Seasawher**
resolve #26

This PR is tested at mk-exercise: https://github.com/Seasawher/mk-exercise

### CODE REVIEW

**Comment by Seasawher** [comment]
I have made a tool to sort semvar in Lean. see [Seasawher/Semver.lean](https://github.com/Seasawher/Semver.lean).

**Comment by Seasawher** [comment]
`scripts/getLatest.ps1` has a following job:

1. download the list of all releases via `gh` command
2. create a file with content of step 1
3. download the binary of Seasawher/semver via gh command
4. run `semver.exe` to update `lean-toolchain`
5. remove temporary files

This is a bit compicated, so simplification may be required. If the process of sorting can be achieved as a PowerShell script, that might be better.

How do you think?

**Comment by kim-em** [comment]
I don't understand why an executables are involved. This should look like a `Semver` type, with appropriate functions to and from strings, and `LE` and `LT` instances.

**Comment by oliver-butterley** [comment]
Thanks @Seasawher for putting together a working version of this idea. I'm not completely comfortable with this solution, rather like you write in your own comment. We should aim for a much cleaner solution. I see two main possibilities:
- A lean based solution but using the already existing [Semver](https://github.com/leanprover/lean4/blob/d6cb2432c6cfb847cdb1921fdbb98bc698835ec4/src/lake/Lake/Util/Version.lean#L18) type. Thanks @semorrison for pointing this out.
- Redo the entire action as javascript/node. This then allows the standard [semver](https://github.com/npm/node-semver) library to be used.
I rather favour the second alternative and can do the overhaul as soon as I manage to get some spare time. It has various other benefits: javascript/node is essentially the native thing for gh actions, the code will be much more maintainable and better user feedback can be done in a manageable way (the [gh toolkit](https://github.com/actions/toolkit) adds substantially to the ease of this and the cleanliness of the code). As a script based action it is already a little ungainly, and being javascript will allow painless scaling of features.

**Comment by Seasawher** [comment]
> Redo the entire action as javascript/node. This then allows the standard semver library to be used.

This sounds nice

**Pull request closed without merging**
